load("@build_stack_rules_hugo//hugo:rules.bzl", "hugo_theme")

hugo_theme(
    name = "gron",
    srcs = glob(["**"]),
    theme_name = "gron",
    visibility = [
        "//visibility:public",
    ],
)
